spring:
  application:
    #应用名称
    name: eureka-client
server:
  #端口号
  port: 8081

eureka:
  client:
    service-url:
        #eureka-server 地址
        defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #服务续约到期时间 单位秒
    lease-expiration-duration-in-seconds: 10
    #服务续约间隔时间 单位秒
    lease-renewal-interval-in-seconds: 5

management:
  health:
    defaults:
      #开启健康检查
      enabled: true